### ISSUE TITLE
Question About Testing

### ISSUE THREAD

**Issue by Shiran-Yuan** [elijahcole/sinr#2] opened 2023-07-29 13:02 UTC
Hi! Thanks for creating and open-sourcing this awesome project. I was wondering something about testing details: how exactly are the points used for calculating MAP values sampled? If this was calculated using the hexagon grid, does it make the testing results biased towards negative results (since there are more negative regions than positive ones)? Thank you in advance for your answer.

**Comment by macaodha** [comment] 2023-07-29 16:27
Hi there! Thanks for your interest in the work and for your kind words.

To answer your question, the negatives are sampled in different ways depending on the dataset used. The construction of the S&T and IUCN datasets are described in sections E1 and E2 on in the supplementary material: 
https://arxiv.org/pdf/2306.02564.pdf  

For the S&T dataset, we do not have confirmed presence or absences for all locations on earth so there is more of a balance between the positives and negatives for each species. For IUCN, on average we have many more negatives per species.  

However, we would note that the different tasks favour different behaviours from the models, e.g. the `Geo Prior` task will reward models that have high recall. Thus a model that mostly predicts absences would do poorly on this task. From Table 1 we observe that there is a correlation in performance across the tasks for a given model (but this does break down as we add more data i.e. the `All` case) . This perhaps indicates that models that are biased towards negatives are not getting rewarded because of the metrics. 

We did not observe a bias towards models that have a tendency to predict more absences that presences.  This is something that could be evaluated using different metrics, which would be an interesting thing to do.

**Comment by macaodha** [comment] 2023-07-29 16:28
I'll close this issues as it is more a discussion one than an issue with the code or data. However, please feel free to follow up here.

**Closed as completed by macaodha** 2023-07-29 16:28 UTC
Labels: discussion
